In [1]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

import pandas as pd

# Validação cruzada

In [2]:
df = pd.read_csv("iris.csv")

In [3]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

Primeiro criamos o conjunto y formado pela saída que queremos prever. E o conjunto X formado pelas covariadas que serão usadas na previsão.

In [4]:
y = df["variety"]
X = df.drop(columns=["variety"])

Agora vamos separar o conjunto em treino e teste.

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=123)

In [6]:
print("Tamanho de X_train:", X_train.shape)
print("Tamanho de X_test:", X_test.shape)
print("Tamanho de Y_train:", y_train.shape)
print("Tamanho de Y_test:", y_test.shape)

Tamanho de X_train: (105, 4)
Tamanho de X_test: (45, 4)
Tamanho de Y_train: (105,)
Tamanho de Y_test: (45,)

Agora vamos usar o conjunto de treino para treinar um modelo de Floresta Aleatória

In [7]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

Primeiro vamos calcular o erro do nosso algorítmo no conjunto de treino.

In [8]:
train_pred = model.predict(X_train)
results_df = pd.DataFrame({'True Labels': y_train, 'Predicted Labels': train_pred})

results_df.head()

    True Labels Predicted Labels
114   Virginica        Virginica
136   Virginica        Virginica
53   Versicolor       Versicolor
19       Setosa           Setosa
38       Setosa           Setosa

In [9]:
train_accuracy = accuracy_score(y_train,train_pred)
print("Acurácia no conjunto de treino:",train_accuracy)

Acurácia no conjunto de treino: 1.0

Agora vamos fazer o mesmo no conjunto de teste.

In [10]:
test_pred = model.predict(X_test)
results_df = pd.DataFrame({'True Labels': y_test, 'Predicted Labels': test_pred})

results_df.head()

    True Labels Predicted Labels
72   Versicolor       Versicolor
112   Virginica        Virginica
132   Virginica        Virginica
88   Versicolor       Versicolor
37       Setosa           Setosa

In [11]:
test_accuracy = accuracy_score(y_test,test_pred)
print("Acurácia no conjunto de teste:",test_accuracy)

Acurácia no conjunto de teste: 0.9555555555555556

Note que a acurácia no teste foi menor que no treino, como esperado.

## K-fold

Agora vamos utilizar a validação cruzada com k-fold.

In [16]:
model = RandomForestClassifier(random_state=42)

cv_scores =  cross_val_score(model,X_train,y_train,cv=5,scoring='accuracy')

mean_train_cv_accuracy = train_cv_scores.mean()
print("A acurácia média usando 5-fold validação cruzada no treino é: ",mean_train_cv_accuracy)

A acurácia média usando 5-fold validação cruzada no treino é:  0.9333333333333333